### PR TITLE
Reorganize test-engineering files

### PR DESCRIPTION
**Pull request by hackebrot**
This pull request moves the tests we formerly referred to as integration and later system tests to a new sub directory in the `test-engineering` directory named `contract-tests`, since that most accurately describes the kind of coverage they provide. 🤖 

The files are now properly separated from the load tests in `tests-engineering/load-tests`.

### CODE REVIEW

**Review by mythmon — APPROVED** [review]
This naming makes more sense. Thanks for organizing this.

Once this is ready to merge, I'll adjust the branch protecting settings to look for the new test name.

**Comment by hackebrot** [comment]
The 4 existing contract tests now pass again.

Missed to update the relative paths in the corresponding `docker-compose.yml` file. 🤖

**Review by ashrivastava-qa — APPROVED** [review]
LGTM 👍

**Comment by hackebrot** [comment]
Hi @mythmon! 👋🏻 

This has been approved and is now ready to be merged.

**Comment by hackebrot** [comment]
Thanks @mythmon! 🥳

**Pull request merged**
