### PR TITLE
feat: check signature of remote-settings content

### LINKED ISSUE #218: Verify Remote Settings content signatures
When we switched from using the `remote-settings-client` Rust library to using Remote Settings directly (CONSVC-1258), we lost the signature verification of the downloaded collection.

In the November RRA (CONSVC-1337), Steph recommend either re-adding this signature verification before the Beta test, or having a timeline for when we would be re-adding the verification.

This signature verification is a defense-in-depth protection that prevents scenarios like an attacker redirecting Merino to pull from a malicious data source by changing its configuration.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1347)
┆epic: merino-beta-experiment

### LINKED ISSUE #264: Allow signature-verification checks to soft-fail
This is tracking the implementation of [this library ticket](https://github.com/mozilla-services/remote-settings-client/issues/165) in the remote-settings-client.

This is required in order for Merino to do signature verification checks and fail gently.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1414)

### PR DESCRIPTION
**Pull request by Dexterp37**
this implements a new signature verifier that performs the signature verification on content coming from remote settings
but exclusively logs errors, still allowing to use any oddly signed content.

Note: you can already verify that this is correctly working since tests don't specify the proper x5u field and so verification is failing (and printing a log).

Fixes #218
Fixes #264

### CODE REVIEW

**Comment by mythmon** [comment]
> This fixes #218 and #264

If you phrase this as 

```
Fixes #XYZ
Fixes #ABC
```

Then it will automatically close the issues. In the current state, the Github parser won't pick up on that.

**Comment by hackebrot** [comment]
We've now merged the contract tests. Do you mind merging the latest `main` to this branch? 🚀

**Comment by Dexterp37** [comment]
> We've now merged the contract tests. Do you mind merging the latest `main` to this branch? 🚀

Not at all, that's a good idea.

**Comment by hackebrot** [comment]
Looks like there is an issue with the verification:
https://app.circleci.com/pipelines/github/mozilla-services/merino/729/workflows/d9919931-e0f6-453c-ac2a-50eb514b8edf/jobs/3326?invite=true#step-105-264

**Comment by Dexterp37** [comment]
> Looks like there is an issue with the verification: https://app.circleci.com/pipelines/github/mozilla-services/merino/729/workflows/d9919931-e0f6-453c-ac2a-50eb514b8edf/jobs/3326?invite=true#step-105-264

Oh, that's actually the signal that this is working as intended :-) Verification is only supposed to log an error in case of problems. The test data does not incude any signature, so that's the expected state!

**Review by mythmon — DISMISSED** [review]

**Review by pjenvey — COMMENTED** [review]
Don't we want these errors [emitted to sentry](https://github.com/mozilla-services/merino/issues/218#issuecomment-982819159)?

**Comment by mythmon** [comment]
I thought that we had Tracing hooked up so that all error lines were automatically reported to sentry, but I can't find that integration now, so I must be misremembering.

**Review by mythmon — CHANGES_REQUESTED** [review]
We should make sure this is reporting the errors to sentry. This might take the form of reporting `tracing::error!` to sentry automatically.

**Comment by pjenvey** [comment]
The `sentry-tracing` crate can accomplish this but I'm not sure it works with our older pinned 0.19 sentry client

**Comment by Dexterp37** [comment]
@mythmon sadly, as @pjenvey pointed out, we can't use `sentry-tracing` because of the pinned version we use (0.19.1). That crate was introduced in [0.23.0](https://github.com/getsentry/sentry-rust/tree/0.23.0/sentry-tracing).

Anyhow, thanks to our use of `anyhow` (heh, couldn't resist), we can use a primitive version of the sentry/anyhow integration. Unfortunately, it doesn't report the backtrace (it was introduced in a later version), and I don't think it makes much sense to hack it together for this case: the two reported errors are fairly specific and it's very easy to identify them from the signature (see the [test](https://sentry.prod.mozaws.net/operations/merino-local/issues/16045846/?query=is%3Aunresolved)).

By testing this a bit more, we identified a bug in the remote-settings-client (see mozilla-services/remote-settings-client#168) and @leplatrem quickly investigated and fixed it.

**Review by mythmon — APPROVED** [review]

**Pull request merged**
