### PR TITLE
Add contract tests for RS provider

### LINKED ISSUE #143: Add contract test coverage for the RemoteSettings provider
The automated system tests for Merino currently only exercise the `WikiFruit` provider.

From `config/ci.yaml`:

```yaml
# The suggestion providers to enable
suggestion_providers:
  test:
    type: "wiki_fruit"
```

This ticket is for developing at least one additional system test that verifies Merino returns matching suggestions from Remote Settings for HTTP requests to the `/api/v1/suggest` API endpoint.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1287)
┆Epic: merino-milestone-1

### PR DESCRIPTION
**Pull request by hackebrot**
This is currently failing locally for me as Merino does not return any suggestions from the RS provider. 🚧 

The tests passed prior to rebasing my changes to the current upstream `main` branch, which included commits for switching to the `remote-settings-client` crate from our custom client implementation:

* #232 

I don't know what the source of this error is yet. It may be worth reverting the client integration and see if the tests then pass to verify that this is indeed caused by the other client.

Please see the thread on Slack for additional context.

Resolve #143

### CODE REVIEW

**Comment by mythmon** [comment]
@hackebrot please rebase this on the branch in #269. If that fixes the problem, lets land both of these PRs and work on getting remote-settings-client re-enabled (perhaps concurrently with the original implementation).

If that doesn't fix the problem, then we should close #269 without merging it, keep the remote-settings-client integration, and figure out how to get these tests passing.

**Comment by hackebrot** [comment]
@mythmon Done. ✅ 

All 5 contract tests passed now after rebasing on `back-to-custom-rs`. 🤔

**Comment by hackebrot** [comment]
I just created #273 to help us debug the issues with the RS client crate.

**Comment by Dexterp37** [comment]
@hackebrot let's kindly wait for merging this. See https://github.com/mozilla-services/merino/pull/269#issuecomment-989578874

**Comment by hackebrot** [comment]
I have now rebased my commits back to `main`, dropped the revert commit 8c94c8085, and cherry-picked the commits to resolve the issues with the new RS client from @Dexterp37's investigation on #273. 🤖 

Here's what we've learned:
* f55d98767 our custom RS client appears to have added a trailing `/` to the base URL for the Kinto attachments server if not present. With the new RS client and no trailing `/` in the Kinto config, Merino produced attachment URLs as `http://kinto-attachments:80main/quicksuggest/<ATTACHMENT>` which caused Merino to fail to download suggestions from RS.
* 4175fc0be our custom RS client must have stripped the port from the icon URLs for suggestions in the response from Merino. The test framework did not expect the port to be included in icon URLs and the URL comparisons failed.

**My recommendation is to verify that what we've learned has no downstream effect on consumers of Merino's API.**

If that's the case, we can close #269 without merging and use the new RS client. I will go ahead and close #273 now because we've figured out the issues (happy to push my local branch if you wish to investigate more @mythmon).

Great work, team! 🚀

**Review by Dexterp37 — APPROVED** [review]
Let's merge this!

**Comment by hackebrot** [comment]
Thanks for the review @Dexterp37! 🥳

**Pull request merged**
