### PR TITLE
fix: Revert remote-settings-client integration

### LINKED ISSUE #268: Back-out remote-settings-client integration
The remote-settings-client integration is causing some strange issues in QA. We should back it out for now. Raphael will add the tests that exercise Remote Settings as a part of the contract-tests, and then we can re-land the remote-settings-client integration, assuming it passes those tests.

This unblocks deploying a version of Merino with the logging updates that we want.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/CONSVC-1421)

### PR DESCRIPTION
**Pull request by mythmon**
* Revert "Merge pull request #232 from Dexterp37/rs-client"
* Revert "Merge pull request #260 from mozilla-services/kinto-url-with-v1"
* Revert "Merge pull request #261 from mozilla-services/feat/259"
* Revert "Merge pull request #262 from mozilla-services/gh-259"

Fixes #268

### CODE REVIEW

**Comment by mythmon** [comment]
Note: this was not a simple revert, since there were multiple interacting PRs between when this landed and now. Please check carefully.

**Comment by Dexterp37** [comment]
@mythmon hey can we hold back this until tomorrow? As per the slack conversation with @jklukas we don't need the logging changes in the short term.

**Comment by mythmon** [comment]
The primary goal here was to unblock #267, which is failing for hard to diagnose reasons only with the new client. Once we have those tests, it will give us more confidence that the new client is working the same as the old one.

**Review by pjenvey — APPROVED** [review]
I'd prefer to diagnose the #267 issue further but I don't have the bandwidth today (or this week) 😢, reverting this is cheap anyway

**Comment by Dexterp37** [comment]
> I'd prefer to diagnose the #267 issue further but I don't have the bandwidth today (or this week) 😢, reverting this is cheap anyway

I'll help diagnosing test failures this morning :) If we won't be able to solve this before your morning, let's merge this :-) /me runs against the clock... (and hits it)

**Comment by Dexterp37** [comment]
Looks like this is no longer required. See #273 .

**Pull request closed without merging**
