### PR TITLE
Debug issue with RS client 🚧

### PR DESCRIPTION
**Pull request by hackebrot**
This pull requests adds the test-eng changes for adding contract tests for the RS provider from #267 but without the commit to revert back to our custom RS client implementation (8c94c8085cefd7e6e4f780acbcc5dc36cc8225b3).

The purpose of this branch is to diagnose the issues we're seeing with Merino not returning any suggestions from RS when using the RS client crate. This is expected to fail on CI. 🤖 

You can run these tests locally from the Merino repository root as follows:

Build the Docker images:

```text
docker-compose -f test-engineering/contract-tests/docker-compose.yml build
```

Run the tests:

```text
docker-compose -f test-engineering/contract-tests/docker-compose.yml up --abort-on-container-exit
```

When making code changes, make sure to rebuild the respective Docker images before running `up`, for example:

```text
docker-compose -f test-engineering/contract-tests/docker-compose.yml build merino
```

You can change the logging level for Merino by updating the level in `config/ci.yaml`, for example:

```yaml
logging:
  # Print logs in a verbose, formatted format
  format: pretty
  # The minimum level that logs should be reported at
  levels: ["TRACE"]
```

### CODE REVIEW

**Comment by hackebrot** [comment]
For visibility, @Dexterp37 asked how to run a single test scenario:

Edit the test invocation on the `client` service in `test-engineering/contract-tests/docker-compose.yml` to use `-k` to select a specific test scenario, for example:

```yaml
    command: >
      /wait-for-it.sh merino:8000 --strict -- pytest -vv -k
      test_merino[multiple_providers__banana]
```

Scenarios are defined here: `test-engineering/contract-tests/volumes/client/scenarios.yml`

You want to either use `multiple_providers__banana` or `remote_settings__coffee`. The others are for the debug provider `WikiFruit` and won't trigger Merino to return suggestions from RS.

**Comment by Dexterp37** [comment]
I spent some time debugging this locally this morning. This turns out to be a missing trailing slash into the docker compose file for the KINTO_ATTACHMENT_URL variable.  This is the same problem that was fixed [in this commit](https://github.com/mozilla-services/merino/pull/232/commits/d482de466a1c49d2f95e5fda74741e0ddbbdb04b). A change to the Kinto server was recently implemented to enforce a trailing slash in the configuration, so this won't be a problem in newer versions.

**Comment by leplatrem** [comment]
> A change to the Kinto server was recently implemented to enforce a trailing slash in the configuration

Yes, this should be part of v27 coming out this week https://github.com/mozilla-services/kinto-dist/pull/1951/files

**Comment by hackebrot** [comment]
Closing as per https://github.com/mozilla-services/merino/pull/267#issuecomment-989840749. Thanks everyone! 🚀

**Pull request closed without merging**
